# increase history
set-option -g history-limit 10000

# enable mouse
set-option -g mouse on

# prevent exiting copy mode after selection with mouse
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x

# start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

# enable vi-like copy paste
setw -g mode-keys vi

# save and restore tmux sessions
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

# initialize TPM; keep this line at the bottom
run '~/.tmux/plugins/tpm/tpm'
